# This is the configuration I use with Liftoff and my Turnigy 9XR Pro
# transmitter. The transmitter is configured with channels in AETR order.

# Total number of channels transmitted by your PPM transmitter.
# If your transmitter sends more channels than you have configured below,
# set this to the total number of channels in the PPM signal.
# For example, if your TX sends 8 channels but you only want to use 6:
#   total_channel_count = 8
# If omitted, defaults to the number of configured channels below.
# total_channel_count = 8

# Channel 1: Roll (Aileron)
[[channels]]
type = "axis"
code = "ABS_RX"

# Channel 2: Pitch (Elevator)
[[channels]]
type = "axis"
code = "ABS_RY"

# Channel 3: Thrust
[[channels]]
type = "axis"
code = "ABS_Y"

# Channel 4: Yaw (Rudder)
[[channels]]
type = "axis"
code = "ABS_X"

# Arm/disarm
[[channels]]
type = "multi"
num_positions = 2
thresholds = [250]
codes = ["BTN_1", "BTN_2"]
hysteresis = 0

# Toggle viewpoint
[[channels]]
type = "button"
code = "BTN_3"
threshold = 250

# Flight mode
# This maps a three-position switch to Toggle Level, Toggle Acro, and Toggle
# Horizon
[[channels]]
type = "multi"
num_positions = 3
thresholds = [250, 350]
codes = ["BTN_5", "BTN_6", "BTN_7"]
hysteresis = 10

# Currently unmapped in liftoff
[[channels]]
type = "multi"
num_positions = 2
thresholds = [250]
codes = ["BTN_8", "BTN_9"]
hysteresis = 10
